"use strict";
exports.__esModule = true;
exports.closeConnection = exports.executeQuery = exports.setConnection = void 0;
var main_1 = require("./pg/main");
var akilyProtocol = new main_1.AkilyProtocol();
var setConnection = akilyProtocol.setConnection;
exports.setConnection = setConnection;
var executeQuery = akilyProtocol.executeQuery;
exports.executeQuery = executeQuery;
var closeConnection = akilyProtocol.closeConnection;
exports.closeConnection = closeConnection;
